services:
  - type: web
    name: telegram-bot-service  # Replace this with your desired service name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    pythonVersion: "3.11"  # Update Python version here
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}  # Securely stored in Render Environment
      - key: WEBHOOK_URL
        value: ${WEBHOOK_URL}  # Securely stored in Render Environment
      - key: ADMIN_ID
        value: ${ADMIN_ID}  # Optional: Securely stored in Render Environment
